/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package servidor.pspro.ej4_carrera_de_motos.vista;

import java.util.ArrayList;
import servidor.pspro.ej4_carrera_de_motos.threads.MotoThread;

/**
 *
 * @author Dam
 */
public class PanelInicial extends javax.swing.JPanel {
    
    private Ventana ventana;
    private MotoThread moto1, moto2;
    private ArrayList<MotoThread> podio;
    
    /**
     * Creates new form PanelInicial
     */
    public PanelInicial(Ventana ventana) {
        initComponents();
        this.ventana = ventana;
        podio = new ArrayList<MotoThread>();
        start();
    }
    
    private void start(){
        moto1 = new MotoThread("moto1", progressMoto1, lblLapsMoto1, lblStateMoto1, 40, 1, 2, podio);
        moto2 = new MotoThread("moto2", progressMoto2, lblLapsMoto2, lblStateMoto2, 40, 1, 2, podio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressMoto1 = new javax.swing.JProgressBar();
        progressMoto2 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblStateMoto1 = new javax.swing.JLabel();
        lblStateMoto2 = new javax.swing.JLabel();
        btnRestart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblLapsMoto1 = new javax.swing.JLabel();
        lblLapsMoto2 = new javax.swing.JLabel();

        progressMoto1.setStringPainted(true);
        progressMoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressMoto1MouseClicked(evt);
            }
        });

        progressMoto2.setStringPainted(true);
        progressMoto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressMoto2MouseClicked(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(0, 255, 153));
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(255, 255, 102));
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jLabel1.setText("Motorbike1:");

        jLabel2.setText("Motorbike2:");

        lblStateMoto1.setText("Thread State");

        lblStateMoto2.setText("Thread State");

        btnRestart.setBackground(new java.awt.Color(255, 153, 153));
        btnRestart.setText("Restart");
        btnRestart.setEnabled(false);
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MOTOS GP");

        lblLapsMoto1.setText("Race Laps");

        lblLapsMoto2.setText("Race Laps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLapsMoto2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStateMoto2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLapsMoto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblStateMoto1))
                            .addComponent(progressMoto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(progressMoto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(btnRestart)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblLapsMoto1)
                    .addComponent(lblStateMoto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblLapsMoto2)
                    .addComponent(lblStateMoto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop)
                    .addComponent(btnRestart))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        moto1.start();
        moto2.start();
        btnStart.setEnabled(false);
        btnRestart.setEnabled(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void progressMoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressMoto1MouseClicked
        if(!btnStart.isEnabled()){
            moto1.setStop(!moto1.isStop());
            if(moto1.isStop()) {
                moto1.suspend();
                lblStateMoto1.setText("Stopped");
            } else {
                moto1.resume();
                lblStateMoto1.setText("Running");
            }
        }
    }//GEN-LAST:event_progressMoto1MouseClicked

    private void progressMoto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressMoto2MouseClicked
        if(!btnStart.isEnabled()){
            moto2.setStop(!moto2.isStop());
            if(moto2.isStop()) {
                moto2.suspend();
                lblStateMoto2.setText("Stopped");
            } else {
                moto2.resume();
                lblStateMoto2.setText("Running");
            }
        }
    }//GEN-LAST:event_progressMoto2MouseClicked

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if(btnStop.getText().equals("Stop") && !btnStart.isEnabled()){
            moto1.setStop(true);
            moto2.setStop(true);
            moto1.suspend();
            moto2.suspend();
            lblStateMoto1.setText("Stopped");
            lblStateMoto2.setText("Stopped");
            btnStop.setText("Continue");
        } else if(btnStop.getText().equals("Continue") && !btnStart.isEnabled()) {
            moto1.setStop(false);
            moto2.setStop(false);
            moto1.resume();
            moto2.resume();
            lblStateMoto1.setText("Running");
            lblStateMoto2.setText("Running");
            btnStop.setText("Stop");
        }
        
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        moto1.suspend();
        moto2.suspend();
        progressMoto1.setValue(0);
        progressMoto2.setValue(0);
        podio.clear();
        start();
        btnRestart.setEnabled(false);
        btnStart.setEnabled(true);
    }//GEN-LAST:event_btnRestartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblLapsMoto1;
    private javax.swing.JLabel lblLapsMoto2;
    private javax.swing.JLabel lblStateMoto1;
    private javax.swing.JLabel lblStateMoto2;
    private javax.swing.JProgressBar progressMoto1;
    private javax.swing.JProgressBar progressMoto2;
    // End of variables declaration//GEN-END:variables
}
