/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package servidor.pspro.ej4_carrera_de_motos.vista;

import servidor.pspro.ej4_carrera_de_motos.threads.MotoThread;

/**
 *
 * @author Dam
 */
public class PanelInicial extends javax.swing.JPanel {
    
    private Ventana ventana;
    private MotoThread moto1, moto2;
    private Thread thr1, thr2;
    
    /**
     * Creates new form PanelInicial
     */
    public PanelInicial(Ventana ventana) {
        initComponents();
        this.ventana = ventana;
        moto1 = new MotoThread("moto1", progressMoto1, 20, 1);
        thr1 = new Thread(moto1);
        moto2 = new MotoThread("moto2", progressMoto2, 20, 3);
        thr2 = new Thread(moto2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressMoto1 = new javax.swing.JProgressBar();
        progressMoto2 = new javax.swing.JProgressBar();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        progressMoto1.setStringPainted(true);
        progressMoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressMoto1MouseClicked(evt);
            }
        });

        progressMoto2.setStringPainted(true);
        progressMoto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                progressMoto2MouseClicked(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(progressMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop))
                .addGap(24, 24, 24)
                .addComponent(progressMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progressMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        thr1.start();
        thr2.start();
        btnStart.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void progressMoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressMoto1MouseClicked
        moto1.setStop(!moto1.isStop());
    }//GEN-LAST:event_progressMoto1MouseClicked

    private void progressMoto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_progressMoto2MouseClicked
        moto2.setStop(!moto2.isStop());
    }//GEN-LAST:event_progressMoto2MouseClicked

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if(btnStop.getText().equals("Stop")){
            moto1.setStop(true);
            moto2.setStop(true);
            btnStop.setText("Continue");
        } else if(btnStop.getText().equals("Continue")) {
            moto1.setStop(false);
            moto2.setStop(false);
            btnStop.setText("Stop");
        }
        
    }//GEN-LAST:event_btnStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JProgressBar progressMoto1;
    private javax.swing.JProgressBar progressMoto2;
    // End of variables declaration//GEN-END:variables
}
